apiVersion: v1
kind: Secret
metadata:
  name: cinemaabyss-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  # Base64 encoded values
  DB_PASSWORD: {{ .Values.database.password }}
  DB_CONNECTION_STRING: {{ printf "postgres://%s:%s@%s:%v/%s?sslmode=disable" .Values.database.user (.Values.database.password | b64dec) .Values.database.host .Values.database.port .Values.database.name | b64enc | quote }}
