apiVersion: v1
kind: Secret
metadata:
  name: cinemaabyss-secrets
  namespace: cinemaabyss
type: Opaque
data:
  # Base64 encoded values
  # echo -n "postgres_password" | base64
  DB_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=
  # echo -n "postgres://postgres:postgres_password@postgres:5432/cinemaabyss?sslmode=disable" | base64
  DB_CONNECTION_STRING: G9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc19wYXNzd29yZEBwb3N0Z3Jlczo1NDMyL2NpbmVtYWFieXNzP3NzbG1vZGU9ZGlzYWJsZQ==
  