{{- if .Values.proxyService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
spec:
  replicas: {{ .Values.proxyService.replicas }}
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      imagePullSecrets:
        - name: dockerconfigjson
      containers:
        - name: proxy-service
          image: {{ .Values.proxyService.image.repository }}:{{ .Values.proxyService.image.tag }}
          imagePullPolicy: {{ .Values.proxyService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.proxyService.service.targetPort }}
          env:
            - name: PORT
              value: "{{ .Values.proxyService.service.targetPort }}"
          envFrom:
            - configMapRef:
                name: cinemaabyss-config
          resources:
{{ toYaml .Values.proxyService.resources | indent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.proxyService.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.proxyService.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
spec:
  selector:
    app: proxy-service
  ports:
    - port: {{ .Values.proxyService.service.port }}
      targetPort: {{ .Values.proxyService.service.targetPort }}
  type: {{ .Values.proxyService.service.type }}
{{- end }}
